"""init

Revision ID: b7324033dc54
Revises: b2f87ea1d553
Create Date: 2026-03-17 14:44:54.993697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7324033dc54'
down_revision: Union[str, Sequence[str], None] = 'b2f87ea1d553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'owner_id')
    # ### end Alembic commands ###
